server:
  port: 8001
  error:
    include-stacktrace: always

spring:
  application:
    name: pharmacy

  datasource:
    url: jdbc:mysql://localhost:3306/pharmacy
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 50


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true